# Generated by Django 4.2.9 on 2024-02-16 14:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.CharField(max_length=64, unique=True)),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Taxon",
            fields=[
                ("taxon_id", models.IntegerField(primary_key=True, serialize=False)),
                ("dataset_id", models.CharField(blank=True, max_length=50)),
                ("accepted_name_usage_id", models.IntegerField(blank=True, null=True)),
                ("original_name_usage_id", models.IntegerField(blank=True, null=True)),
                ("scientific_name", models.CharField(blank=True, max_length=300)),
                ("scientific_name_authorship", models.CharField(blank=True, max_length=300)),
                ("canonical_name", models.CharField(blank=True, max_length=100)),
                ("generic_name", models.CharField(blank=True, max_length=100)),
                ("specific_epithet", models.CharField(blank=True, max_length=100)),
                ("infraspecific_epithet", models.CharField(blank=True, max_length=100)),
                ("taxon_rank", models.CharField(blank=True, max_length=50)),
                ("name_published_in", models.CharField(blank=True, max_length=1000)),
                ("taxonomic_status", models.CharField(blank=True, max_length=50)),
                ("taxon_remarks", models.CharField(blank=True, max_length=200)),
                ("kingdom", models.CharField(blank=True, max_length=50)),
                ("phylum", models.CharField(blank=True, max_length=50)),
                ("taxon_class", models.CharField(blank=True, max_length=50)),
                ("taxon_order", models.CharField(blank=True, max_length=50)),
                ("taxon_family", models.CharField(blank=True, max_length=50)),
                ("genus", models.CharField(blank=True, max_length=50)),
                (
                    "parent_name_usage",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="taxonomy.taxon"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Morphospecies",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_modified", models.DateTimeField(auto_created=True, auto_now=True)),
                ("name", models.CharField(max_length=64, unique=True)),
                ("defunt_date", models.DateTimeField(null=True)),
                ("taxon_class", models.CharField(blank=True, max_length=64, null=True)),
                ("order", models.CharField(blank=True, max_length=64, null=True)),
                ("family", models.CharField(blank=True, max_length=64, null=True)),
                ("subfamily", models.CharField(blank=True, max_length=64, null=True)),
                ("genus", models.CharField(blank=True, max_length=64, null=True)),
                ("species", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "bypass",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "defunt_morpho",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="taxonomy.morphospecies"
                    ),
                ),
                (
                    "defunt_user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "taxon",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="taxonomy.taxon"
                    ),
                ),
            ],
            options={
                "verbose_name": "Morphospecies",
                "verbose_name_plural": "Morphospecies",
                "permissions": [
                    (
                        "use_morphospecies_functions",
                        "Can use the “Merge” button, check the “Bypass” box or change the percent threshold",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AiTraining",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total", models.IntegerField()),
                ("precision", models.FloatField()),
                ("recall", models.FloatField()),
                ("f1", models.FloatField()),
                ("tp", models.IntegerField()),
                ("fp", models.IntegerField()),
                ("tn", models.IntegerField()),
                ("fn", models.IntegerField()),
                ("train", models.IntegerField()),
                ("test", models.IntegerField()),
                ("val", models.IntegerField()),
                ("model", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="taxonomy.aiversion")),
                (
                    "morphospecies",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="taxonomy.morphospecies"),
                ),
            ],
        ),
    ]
