# Generated by Django 4.2.14 on 2024-07-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="morphospecies",
            options={},
        ),
        migrations.RenameField(
            model_name="aiversion",
            old_name="date",
            new_name="entered_date",
        ),
        migrations.RemoveField(
            model_name="morphospecies",
            name="bypass",
        ),
        migrations.RemoveField(
            model_name="morphospecies",
            name="family",
        ),
        migrations.RemoveField(
            model_name="morphospecies",
            name="genus",
        ),
        migrations.RemoveField(
            model_name="morphospecies",
            name="order",
        ),
        migrations.RemoveField(
            model_name="morphospecies",
            name="species",
        ),
        migrations.RemoveField(
            model_name="morphospecies",
            name="taxon",
        ),
        migrations.RemoveField(
            model_name="morphospecies",
            name="taxon_class",
        ),
        migrations.AddField(
            model_name="morphospecies",
            name="gbif_canonical_name",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="morphospecies",
            name="gbif_class",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="morphospecies",
            name="gbif_family",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="morphospecies",
            name="gbif_genus",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="morphospecies",
            name="gbif_key",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="morphospecies",
            name="gbif_order",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="morphospecies",
            name="gbif_phylum",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="morphospecies",
            name="gbif_rank",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="morphospecies",
            name="gbif_scientific_name",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="morphospecies",
            name="gbif_species",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="morphospecies",
            name="gbif_status",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="morphospecies",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="morpho_images/"),
        ),
        migrations.AddField(
            model_name="morphospecies",
            name="image_thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="morpho_images/"),
        ),
        migrations.AlterField(
            model_name="morphospecies",
            name="note",
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="morphospecies",
            name="subfamily",
            field=models.CharField(blank=True, default="", max_length=64),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Taxon",
        ),
    ]
