# Generated by Django 4.2.14 on 2024-08-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0002_alter_morphospecies_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="morphospecies",
            name="update_thumbs",
            field=models.BooleanField(null=True),
        ),
    ]
