# Generated by Django 5.0.9 on 2024-12-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_morphospecies_update_thumbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitraining',
            name='model_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
