# Generated by Django 5.0.9 on 2024-12-13 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0004_aitraining_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitraining',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxonomy.aiversion'),
        ),
    ]
