# Generated by Django 5.0.9 on 2024-12-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0005_populate_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitraining',
            name='model_name',
            field=models.CharField(max_length=64),
        ),
    ]
