# Generated by Django 5.0.9 on 2024-12-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0006_alter_aitraining_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitraining',
            name='entered_date',
            field=models.DateField(null=True),
        ),
    ]
