# Generated by Django 5.0.9 on 2024-12-19 19:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0008_populate_ai_entered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitraining',
            name='entered_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
