# Generated by Django 5.1.4 on 2025-01-07 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0009_alter_aitraining_entered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aitraining',
            name='model',
        ),
    ]
