# Generated by Django 5.1.4 on 2025-01-07 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0010_remove_aitraining_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AiVersion',
        ),
    ]
