# Generated by Django 5.1.4 on 2025-02-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0011_delete_aiversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='morphospecies',
            name='exclude_from_export',
            field=models.BooleanField(default=False),
        ),
    ]
