# Generated by Django 5.1.4 on 2025-04-25 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0012_morphospecies_exclude_from_export'),
    ]

    operations = [
        migrations.CreateModel(
            name='GBIFImageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gbif_taxon_key', models.IntegerField()),
                ('scientific_name', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=500)),
                ('media_type', models.CharField(blank=True, max_length=100, null=True)),
                ('license', models.CharField(blank=True, max_length=255, null=True)),
                ('date_fetched', models.DateTimeField(auto_now_add=True)),
                ('decimal_latitude', models.FloatField(blank=True, null=True)),
                ('decimal_longitude', models.FloatField(blank=True, null=True)),
                ('occurrence_id', models.BigIntegerField(blank=True, null=True)),
                ('downloaded_image', models.BooleanField(default=False)),
                ('morphospecies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.morphospecies')),
            ],
        ),
    ]
