# Generated by Django 5.2.3 on 2025-11-24 16:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0014_filteredgbifimagerecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="morphospecies",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=1000),
                default=list,
                size=None,
            ),
        ),
    ]
