# Generated by Django 5.2.3 on 2026-04-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0017_morphospecies_taxonomy_review_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="morphospecies",
            name="taxonomy_unable_to_identify",
            field=models.BooleanField(default=False, verbose_name="Reviewed"),
        ),
    ]
