volumes:
  production_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    container_name: bugbox3_local_django
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 9g
    depends_on:
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgrescloud
      - ./.envs/.local/.secrets
    ports:
      - '8002:8002'
    command: /start

  redis:
    image: docker.io/redis:7.2
    container_name: bugbox3_local_redis
    deploy:
      resources:
        limits:
          memory: 9g
    command: --port 6380
    ports:
      - "6380:6380"
    volumes:
      - production_redis_data:/data

  celeryworker:
    <<: *django
    container_name: bugbox3_local_celeryworker
    deploy:
      resources:
        limits:
          memory: 9g
    depends_on:
      - redis
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    container_name: bugbox3_local_celerybeat
    deploy:
      resources:
        limits:
          memory: 9g
    depends_on:
      - redis
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    container_name: bugbox3_local_flower
    deploy:
      resources:
        limits:
          memory: 9g
    depends_on:
      - redis
    ports:
      - '5556:5556'
    command: /start-flower

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: mikaylaelectra/ecdysis_node
    container_name: bugbox3_local_node
    deploy:
      resources:
        limits:
          memory: 9g
    depends_on:
      - django
    volumes:
      - .:/app:z
      # https://jdlm.info/articles/2019/09/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - '3000:3000'
