volumes:
  production_redis_data: {}
  static_volume:

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    container_name: bugbox3_production_django
    image: bugbox3_production_django
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 9g
    depends_on:
      - redis
    volumes:
      - static_volume:/app/staticfiles
      - /pool1/srv/bugbox3/bugbox3/media:/mounted_local_media
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgrescloud
      - ./.envs/.local/.secrets
      - ./.envs/.local/.localproduction
    expose:
      - "8000"
    command: /start

  redis:
    image: docker.io/redis:7.2
    container_name: bugbox3_production_redis
    deploy:
      resources:
        limits:
          memory: 9g
    command: --port 6380
    ports:
      - "6380:6380"
    volumes:
      - production_redis_data:/data

  celeryworker:
    container_name: bugbox3_production_celeryworker
    image: bugbox3_production_django
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 9g
    depends_on:
      - redis
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgrescloud
      - ./.envs/.local/.secrets
      - ./.envs/.local/.localproduction
    ports: []
    command: /start-celeryworker

  celerybeat:
    container_name: bugbox3_production_celerybeat
    image: bugbox3_production_django
    deploy:
      resources:
        limits:
          memory: 9g
    depends_on:
      - redis
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgrescloud
      - ./.envs/.local/.secrets
      - ./.envs/.local/.localproduction
    ports: []
    command: /start-celerybeat

  flower:
    container_name: bugbox3_production_flower
    image: bugbox3_production_django
    deploy:
      resources:
        limits:
          memory: 9g
    depends_on:
      - redis
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgrescloud
      - ./.envs/.local/.secrets
      - ./.envs/.local/.localproduction
    ports:
      - '5556:5556'
    command: /start-flower

  nginx:
    build: ./compose/production/nginx
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - ./.envs/.local/.localproduction
    ports:
      - 3000:80
    depends_on:
      - django
