volumes:
  bugbox3_local_postgres_data: {}
  bugbox3_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    container_name: bugbox3_local_django
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      # - ./.envs/.local/.secrets
    ports:
      - '8002:8002'
    command: /start

  postgres:
    shm_size: 2gb
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    container_name: bugbox3_local_postgres
    volumes:
      - bugbox3_local_postgres_data:/var/lib/postgresql/data
      - bugbox3_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5435:5434"
    command:
      -p 5434

  redis:
    image: docker.io/redis:6
    container_name: bugbox3_local_redis
    command: --port 6380
    ports:
      - "6380:6380"

  celeryworker:
    <<: *django
    container_name: bugbox3_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    container_name: bugbox3_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    container_name: bugbox3_local_flower
    ports:
      - '5556:5556'
    command: /start-flower

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    container_name: bugbox3_local_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # https://jdlm.info/articles/2019/09/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - '3000:3000'
