# Generated by Django 5.2.3 on 2025-10-14 15:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CSVImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("import_date", models.DateTimeField(auto_now_add=True)),
                ("total_records", models.IntegerField(default=0)),
                ("successful_records", models.IntegerField(default=0)),
                ("failed_records", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("error_log", models.TextField(blank=True)),
                (
                    "imported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CSV Import Log",
                "verbose_name_plural": "CSV Import Logs",
                "ordering": ["-import_date"],
            },
        ),
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm",
                "verbose_name_plural": "Farms",
                "ordering": ["name"],
                "permissions": [("manage_farms", "Can manage farms")],
                "unique_together": {("grower", "name")},
            },
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=200)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("crop", "Crop Field"),
                            ("range", "Rangeland/Pasture"),
                            ("orchard", "Orchard"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Field latitude (-90 to 90)",
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Field longitude (-180 to 180)",
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "crop_variety",
                    models.CharField(
                        blank=True,
                        help_text="For crop fields and orchards",
                        max_length=200,
                    ),
                ),
                (
                    "forage_varieties",
                    models.CharField(
                        blank=True, help_text="For rangeland", max_length=500
                    ),
                ),
                (
                    "paddock_size",
                    models.CharField(
                        blank=True, help_text="For rangeland", max_length=100
                    ),
                ),
                (
                    "rootstock_species",
                    models.CharField(
                        blank=True, help_text="For orchards", max_length=500
                    ),
                ),
                (
                    "transitional_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1st_year", "1st year"),
                            ("2nd_year", "2nd year"),
                            ("3rd_year", "3rd year"),
                            ("4th_year", "4th year"),
                        ],
                        help_text="For orchards",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="grower_portal.farm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field",
                "verbose_name_plural": "Fields",
                "ordering": ["farm", "field_name"],
                "permissions": [("manage_fields", "Can manage fields")],
                "unique_together": {("farm", "field_name")},
            },
        ),
        migrations.CreateModel(
            name="GrowerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submission_code", models.CharField(max_length=50, unique=True)),
                ("is_draft", models.BooleanField(default=True)),
                ("is_submitted", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("application_year", models.IntegerField()),
                (
                    "transect_code_1",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "transect_code_2",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "transect_code_3",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "transect_code_4",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="grower_portal.field",
                    ),
                ),
                (
                    "grower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Grower Application",
                "verbose_name_plural": "Grower Applications",
                "ordering": ["-application_year", "-created_at"],
                "permissions": [
                    ("manage_grower_applications", "Can manage grower applications")
                ],
                "unique_together": {("field", "application_year")},
            },
        ),
        migrations.CreateModel(
            name="ApplicationMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transect_number",
                    models.IntegerField(
                        help_text="1-4 within application (corresponds to application's transect codes)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "acres_sampled",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "years_under_management",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("supports_dairy", models.BooleanField(default=False)),
                (
                    "is_confined_dairy",
                    models.BooleanField(default=False, help_text="For crop fields"),
                ),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="grower_portal.growerapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Measurement",
                "verbose_name_plural": "Application Measurements",
                "ordering": ["application", "transect_number"],
                "permissions": [
                    (
                        "view_application_measurements",
                        "Can view application measurements",
                    ),
                    (
                        "add_application_measurements",
                        "Can add application measurements",
                    ),
                    (
                        "change_application_measurements",
                        "Can change application measurements",
                    ),
                    (
                        "delete_application_measurements",
                        "Can delete application measurements",
                    ),
                ],
                "unique_together": {("application", "transect_number")},
            },
        ),
        migrations.CreateModel(
            name="GrowerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Age in years",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                (
                    "race",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "american_indian_alaska_native",
                                "American Indian or Alaska Native",
                            ),
                            ("asian", "Asian"),
                            ("black_african_american", "Black or African American"),
                            (
                                "native_hawaiian_pacific_islander",
                                "Native Hawaiian or Other Pacific Islander",
                            ),
                            ("white", "White"),
                            ("two_or_more_races", "Two or More Races"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "profile_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the initial profile completion has been done",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grower_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Grower Profile",
                "verbose_name_plural": "Grower Profiles",
                "permissions": [
                    ("manage_grower_profiles", "Can manage grower profiles")
                ],
            },
        ),
        migrations.CreateModel(
            name="GrowerReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_file", models.FileField(upload_to="grower_reports/")),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("email_sent", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="grower_portal.growerapplication",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Grower Report",
                "verbose_name_plural": "Grower Reports",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="ManagementPractices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uses_tillage", models.BooleanField(default=False)),
                ("tillage_depth", models.CharField(blank=True, max_length=50)),
                ("uses_cover_crop", models.BooleanField(default=False)),
                (
                    "cover_crop_termination",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Grazing, Tillage, Other",
                        max_length=100,
                    ),
                ),
                ("uses_synthetic_fertilizers", models.BooleanField(default=False)),
                ("uses_synthetic_insecticides", models.BooleanField(default=False)),
                ("uses_synthetic_herbicides", models.BooleanField(default=False)),
                ("uses_synthetic_fungicides", models.BooleanField(default=False)),
                ("uses_organic_amendments", models.BooleanField(default=False)),
                (
                    "organic_amendment_types",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Manure, Compost, Compost Tea, Organic Fertilizer",
                        max_length=500,
                    ),
                ),
                ("uses_grazing", models.BooleanField(default=False)),
                (
                    "grazer_types",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Chickens, Livestock",
                        max_length=200,
                    ),
                ),
                ("applies_insecticides_dewormers", models.BooleanField(default=False)),
                (
                    "insecticide_dewormer_frequency",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Not used, Once per year, Multiple times per year",
                        max_length=100,
                    ),
                ),
                ("allows_ground_cover", models.BooleanField(default=False)),
                (
                    "ground_cover_management",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Tilling, Herbicide, Other",
                        max_length=100,
                    ),
                ),
                ("tills_between_rows", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practices",
                        to="grower_portal.field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Management Practices",
                "verbose_name_plural": "Management Practices",
            },
        ),
        migrations.CreateModel(
            name="TransectCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transect_code", models.CharField(max_length=20, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transect Code",
                "verbose_name_plural": "Transect Codes",
                "ordering": ["transect_code"],
                "permissions": [
                    ("generate_transect_codes", "Can generate transect codes")
                ],
            },
        ),
        migrations.CreateModel(
            name="GrazingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_number",
                    models.IntegerField(
                        help_text="1, 2, 3, or 4",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "rest_period_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Rest period between grazing events in days",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(365),
                        ],
                    ),
                ),
                (
                    "class_of_animal",
                    models.CharField(
                        help_text="e.g., Cow/calf pair, yearling cattle, ewe/lamb pair",
                        max_length=100,
                    ),
                ),
                (
                    "number_of_animals",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "average_weight_lbs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5000),
                        ],
                    ),
                ),
                (
                    "duration_days",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(365),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application_measurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grazing_events",
                        to="grower_portal.applicationmeasurement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grazing Event",
                "verbose_name_plural": "Grazing Events",
                "ordering": ["application_measurement", "event_number"],
                "unique_together": {("application_measurement", "event_number")},
            },
        ),
    ]
