# Generated by Django 5.2.3 on 2025-10-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grower_portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="growerapplication",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="growerapplication",
            name="date_sampled",
            field=models.DateField(
                blank=True, help_text="Date when samples were collected", null=True
            ),
        ),
        migrations.RemoveField(
            model_name="growerapplication",
            name="application_year",
        ),
        migrations.AlterModelOptions(
            name="growerapplication",
            options={
                "ordering": ["-date_sampled", "-created_at"],
                "permissions": [
                    ("manage_grower_applications", "Can manage grower applications")
                ],
                "verbose_name": "Grower Application",
                "verbose_name_plural": "Grower Applications",
            },
        ),
        migrations.AlterUniqueTogether(
            name="growerapplication",
            unique_together={("field", "date_sampled")},
        ),
    ]
