# Generated by Django 5.2.3 on 2025-10-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grower_portal", "0002_alter_growerapplication_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="managementpractices",
            name="insecticide_dewormer_comments",
            field=models.TextField(
                blank=True, help_text="Timing details, name of insecticide/dewormer"
            ),
        ),
        migrations.AlterField(
            model_name="managementpractices",
            name="insecticide_dewormer_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_used", "Not used/less than 10% of herd"),
                    ("once_per_year", "Once per year, not during grazing"),
                    (
                        "multiple_times",
                        "Multiple times per year, and/or during grazing season",
                    ),
                ],
                help_text="Frequency of insecticide/dewormer application",
                max_length=100,
            ),
        ),
    ]
