# Generated by Django 5.2.3 on 2025-10-22 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grower_portal", "0004_add_transect_gps_coordinates"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="acres_sampled",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total acres sampled for this field",
                max_digits=8,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(10000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="field",
            name="is_confined_dairy",
            field=models.BooleanField(
                default=False,
                help_text="Is this a confined dairy operation? (For crop fields)",
            ),
        ),
        migrations.AddField(
            model_name="field",
            name="measurement_comments",
            field=models.TextField(
                blank=True, help_text="Additional comments about field measurements"
            ),
        ),
        migrations.AddField(
            model_name="field",
            name="supports_dairy",
            field=models.BooleanField(
                default=False, help_text="Does this field support dairy operations?"
            ),
        ),
        migrations.AddField(
            model_name="field",
            name="years_under_management",
            field=models.IntegerField(
                blank=True,
                help_text="Years this field has been under current management",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
