# Generated by Django 5.2.3 on 2025-10-23 15:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grower_portal", "0012_add_crop_type_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="acres_sampled",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total acres sampled for this field",
                max_digits=8,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(10000),
                ],
                verbose_name="Number of acres in field sampled",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="crop_variety",
            field=models.CharField(
                blank=True,
                help_text="For crop fields and orchards (deprecated - use crop_type)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("crop", "Crop field"),
                    ("orchard", "Orchard/vineyard/woody crop"),
                    ("range", "Rangeland/pasture"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="is_confined_dairy",
            field=models.BooleanField(
                default=False, help_text="Is this a confined dairy operation?"
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="measurement_comments",
            field=models.TextField(
                blank=True,
                help_text="Additional comments about field measurements",
                verbose_name="Name of insecticide/dewormer and any other comments",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="years_under_management",
            field=models.IntegerField(
                blank=True,
                help_text="Years this field has been under current management",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Number of years under current type of management",
            ),
        ),
        migrations.AlterField(
            model_name="managementpractices",
            name="cover_crop_termination",
            field=models.CharField(
                blank=True,
                choices=[
                    ("grazing", "Grazing"),
                    ("mowing", "Mowing"),
                    ("tillage", "Tillage"),
                    ("herbicide", "Herbicide"),
                    ("other", "Other"),
                ],
                help_text="Method used to terminate cover crops",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="managementpractices",
            name="organic_amendment_types",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manure", "Manure"),
                    ("compost", "Compost"),
                    ("compost_tea", "Compost tea"),
                    ("organic_fertilizer", "Organic fertilizer"),
                    ("other", "Other"),
                ],
                help_text="Type of organic amendments used",
                max_length=500,
                verbose_name="Organic Amendment Types",
            ),
        ),
        migrations.AlterField(
            model_name="managementpractices",
            name="uses_synthetic_fungicides",
            field=models.BooleanField(
                default=False,
                verbose_name="Synthetic Fungicides or fungicide treated seed?",
            ),
        ),
        migrations.AlterField(
            model_name="managementpractices",
            name="uses_synthetic_insecticides",
            field=models.BooleanField(
                default=False,
                verbose_name="Synthetic Insecticides or insecticide treated seed?",
            ),
        ),
        migrations.AlterField(
            model_name="transectcode",
            name="used_in_application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="used_transect_codes",
                to="grower_portal.growerapplication",
            ),
        ),
    ]
