# Generated by Django 5.2.3 on 2025-10-23 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grower_portal", "0013_update_field_labels_and_choices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="field",
            name="crop_variety",
        ),
        migrations.AlterField(
            model_name="field",
            name="years_under_management",
            field=models.IntegerField(
                blank=True,
                help_text="Years this field has been under current management",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(500),
                ],
                verbose_name="Number of years under current type of management",
            ),
        ),
    ]
