# Generated by Django 5.2.3 on 2025-10-23 20:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grower_portal", "0016_orchard_field_customizations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grazingevent",
            name="average_weight_lbs",
        ),
        migrations.RemoveField(
            model_name="grazingevent",
            name="class_of_animal",
        ),
        migrations.RemoveField(
            model_name="grazingevent",
            name="duration_days",
        ),
        migrations.RemoveField(
            model_name="grazingevent",
            name="number_of_animals",
        ),
        migrations.RemoveField(
            model_name="grazingevent",
            name="rest_period_days",
        ),
        migrations.AddField(
            model_name="field",
            name="pasture_size",
            field=models.CharField(
                blank=True,
                help_text="For rangeland - total pasture size in acres",
                max_length=100,
                verbose_name="Pasture size (acres)",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="acres_sampled",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total acres sampled for this field",
                max_digits=8,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(10000),
                ],
                verbose_name="Acres sampled",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="paddock_size",
            field=models.CharField(
                blank=True,
                help_text="For rangeland",
                max_length=100,
                verbose_name="Paddock size (acres)",
            ),
        ),
        migrations.CreateModel(
            name="GrazingEventAnimal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_of_animal",
                    models.CharField(
                        help_text="e.g., Cow/calf pair, yearling cattle, ewe/lamb pair",
                        max_length=100,
                    ),
                ),
                (
                    "number_of_animals",
                    models.IntegerField(
                        help_text="Number of animals in this class",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "average_weight_lbs",
                    models.IntegerField(
                        help_text="Average weight per animal in lbs",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5000),
                        ],
                    ),
                ),
                (
                    "duration_days",
                    models.IntegerField(
                        help_text="Duration of grazing in days",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(365),
                        ],
                    ),
                ),
                (
                    "rest_period_days",
                    models.IntegerField(
                        help_text="Rest period after grazing in days",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(365),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "grazing_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animals",
                        to="grower_portal.grazingevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grazing Event Animal",
                "verbose_name_plural": "Grazing Event Animals",
                "ordering": ["id"],
            },
        ),
    ]
