# Generated by Django 5.2.3 on 2025-10-27 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grower_portal", "0017_rangeland_field_customizations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="grazingevent",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="growerapplication",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="grazingevent",
            constraint=models.UniqueConstraint(
                fields=("application", "event_number"),
                name="unique_application_event_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="growerapplication",
            constraint=models.UniqueConstraint(
                fields=("field", "date_sampled"), name="unique_field_date_sampled"
            ),
        ),
    ]
