# Generated by Django 5.2.3 on 2025-10-27 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grower_portal", "0018_replace_unique_together_with_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="farm",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="field",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="farm",
            constraint=models.UniqueConstraint(
                fields=("grower", "name"), name="unique_grower_farm_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="field",
            constraint=models.UniqueConstraint(
                fields=("farm", "field_name"), name="unique_farm_field_name"
            ),
        ),
    ]
