# Generated by Django 5.2.3 on 2025-10-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grower_portal", "0019_replace_remaining_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="grazingevent",
            name="start_date",
            field=models.DateField(
                blank=True, help_text="Start date of grazing event", null=True
            ),
        ),
        migrations.AddField(
            model_name="managementpractices",
            name="grazed_by_livestock_plan",
            field=models.BooleanField(
                default=False,
                help_text="Grazed by livestock as part of typical management plan",
            ),
        ),
        migrations.AddField(
            model_name="managementpractices",
            name="grazed_current_year",
            field=models.BooleanField(
                default=False, help_text="Grazed in current year"
            ),
        ),
        migrations.AddField(
            model_name="managementpractices",
            name="not_grazed_comments",
            field=models.TextField(
                blank=True,
                help_text="If not grazed in current year, explain",
                null=True,
            ),
        ),
    ]
