# Generated by Django 5.2.3 on 2025-10-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grower_portal", "0020_grazingevent_start_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="field",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="field",
            name="longitude",
        ),
    ]
