# Generated by Django 5.2.3 on 2025-10-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grower_portal", "0021_remove_field_latitude_remove_field_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="measurement_comments",
            field=models.TextField(
                blank=True,
                help_text="General comments about the field",
                verbose_name="Field comments",
            ),
        ),
    ]
