# Generated by Django 5.2.3 on 2025-10-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grower_portal", "0022_alter_field_measurement_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="growerapplication",
            name="grazing_start_date",
            field=models.DateField(
                blank=True,
                help_text="Start date (estimate) when grazing events began",
                null=True,
            ),
        ),
    ]
