# Generated by Django 5.2.3 on 2025-10-30 17:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grower_portal", "0023_growerapplication_grazing_start_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransectMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transect_index",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ]
                    ),
                ),
                ("transect_code", models.CharField(blank=True, max_length=20)),
                ("general_time", models.CharField(blank=True, max_length=50)),
                (
                    "temperature_c",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "wind_speed_ms",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "field_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("wet", "Wet"),
                            ("dry", "Dry"),
                            ("average", "Average"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transect_measurements",
                        to="grower_portal.growerapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["application", "transect_index"],
                "unique_together": {("application", "transect_index")},
            },
        ),
        migrations.CreateModel(
            name="SoilReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("moisture_pct", "Soil Moisture %"),
                            ("temp_c", "Soil Temperature (°C)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("position_m", models.IntegerField()),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "measurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soil",
                        to="grower_portal.transectmeasurement",
                    ),
                ),
            ],
            options={
                "ordering": ["metric", "position_m"],
            },
        ),
        migrations.CreateModel(
            name="SoilCompactionReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_m", models.IntegerField()),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                (
                    "hp",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "measurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compaction",
                        to="grower_portal.transectmeasurement",
                    ),
                ),
            ],
            options={
                "ordering": ["position_m"],
            },
        ),
        migrations.CreateModel(
            name="InfiltrometerReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_mark", models.CharField(max_length=10)),
                ("volume_ml", models.IntegerField(blank=True, null=True)),
                (
                    "measurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="infiltrometer",
                        to="grower_portal.transectmeasurement",
                    ),
                ),
            ],
            options={
                "ordering": ["time_mark"],
            },
        ),
        migrations.CreateModel(
            name="InfiltrationRingReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pour_number",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ]
                    ),
                ),
                (
                    "start_depth_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("infiltration_time_sec", models.IntegerField(blank=True, null=True)),
                (
                    "depth_after_15min_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "change_in_depth_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "measurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="infiltration_ring",
                        to="grower_portal.transectmeasurement",
                    ),
                ),
            ],
            options={
                "ordering": ["pour_number"],
            },
        ),
        migrations.CreateModel(
            name="DropPlateReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance_m", models.IntegerField()),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "measurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drop_plate",
                        to="grower_portal.transectmeasurement",
                    ),
                ),
            ],
            options={
                "ordering": ["distance_m"],
            },
        ),
        migrations.CreateModel(
            name="VegetationReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("green_cover", "Green Cover %"),
                            ("total_groundcover", "Total Groundcover %"),
                            (
                                "plant_richness_no_crop",
                                "Plant Species Richness (no crops)",
                            ),
                            (
                                "plant_richness_with_crop",
                                "Plant Species Richness (with crops)",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("position_m", models.IntegerField()),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "measurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vegetation",
                        to="grower_portal.transectmeasurement",
                    ),
                ),
            ],
            options={
                "ordering": ["metric", "position_m"],
            },
        ),
    ]
