# Generated by Django

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0024_transectmeasurement_soilreading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='uses_broad_fork',
        ),
        migrations.AddField(
            model_name='field',
            name='tillage_methods',
            field=models.CharField(blank=True, help_text='Tillage = any type of mechanical disturbance of the soil (e.g., disk, shanks, basket weed, broad fork, harrow, etc.)', max_length=500, verbose_name='Tillage Methods'),
        ),
        migrations.AddField(
            model_name='field',
            name='orchard_crop_specify',
            field=models.CharField(blank=True, help_text='Specify the type of fruit or nut trees', max_length=200, verbose_name='Specify'),
        ),
        migrations.AlterField(
            model_name='grazingeventanimal',
            name='duration_days',
            field=models.IntegerField(help_text='Grazing days', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Grazing days'),
        ),
    ]

