# Generated by Django 5.2.3 on 2025-11-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grower_portal", "0025_update_crop_types_remove_broad_fork"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="crop_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("row_crop", "Row crop"),
                    ("mixed_veg", "Mixed Vegetables/herbs/specialty crops"),
                    ("hayfield", "Hayfield/Cover crop"),
                    ("cash_crop_cover", "Cash crop with cover crop"),
                ],
                help_text="Type of crop grown",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="managementpractices",
            name="grazed_by_livestock_plan",
            field=models.BooleanField(
                default=False,
                help_text="Grazed by livestock as part of typical management plan",
                verbose_name="Grazed by livestock as part of typical management plan",
            ),
        ),
    ]
