# Generated by Django 5.2.3 on 2025-12-02 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grower_portal", "0026_alter_field_crop_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSVImportFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=200)),
                ("field_value", models.CharField(max_length=255)),
                ("row_number", models.IntegerField(null=True, blank=True)),
                (
                    "import_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="grower_portal.csvimportlog",
                    ),
                ),
                (
                    "transect_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="grower_portal.transectcode",
                    ),
                ),
            ],
            options={
                "verbose_name": "CSV Import Field Value",
                "verbose_name_plural": "CSV Import Field Value",
                "ordering": ["import_log", "transect_code", "field_name"],
            },
        ),
    ]
