# Generated by Django 5.2.3 on 2025-12-04 15:42

import json
from django.db import migrations, models


def convert_error_log_to_json(apps, schema_editor):
    """Convert existing string error_log values to JSON format"""
    CSVImportLog = apps.get_model("grower_portal", "CSVImportLog")

    for log in CSVImportLog.objects.all():
        # If error_log is a string, convert it to JSON format
        if isinstance(log.error_log, str):
            json_data = [{
                "row_number": None,
                "error": log.error_log,
                "row_data": None
            }]
            log.error_log = json.dumps(json_data)
            log.save(update_fields=['error_log'])

def reverse_convert_error_log(apps, schema_editor):
    """Reverse migration: convert JSON back to string (if needed)"""
    CSVImportLog = apps.get_model("grower_portal", "CSVImportLog")

    for log in CSVImportLog.objects.all():
        if log.error_log:
            log.error_log = str(log.error_log)
            log.save(update_fields=['error_log'])


class Migration(migrations.Migration):

    dependencies = [
        ("grower_portal", "0027_csvimportfieldvalue"),
    ]

    operations = [
        migrations.RunPython(
            convert_error_log_to_json,
            reverse_convert_error_log,
        ),
        migrations.AlterField(
            model_name="csvimportlog",
            name="error_log",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
