# Generated by Django 5.2.3 on 2025-12-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grower_portal", "0028_alter_csvimportlog_error_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvimportlog",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="csvimportlog",
            name="file_path",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
