# Generated by Django 5.2.3 on 2025-12-10 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grower_portal", "0028_alter_csvimportlog_error_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("avalanche", "Avalanche"),
                            ("1000_farms", "1000 Farms"),
                        ],
                        help_text="Project type (Avalanche or 1000 Farms)",
                        max_length=20,
                    ),
                ),
                (
                    "label_category",
                    models.CharField(
                        choices=[("inner", "Inner labels"), ("outer", "Outer labels")],
                        help_text="Label category (Inner or Outer)",
                        max_length=20,
                    ),
                ),
                (
                    "cluster_number",
                    models.CharField(
                        help_text="Cluster number (e.g., C1, C2)", max_length=10
                    ),
                ),
                ("year", models.IntegerField(help_text="Year for the labels")),
                (
                    "sample_types",
                    models.JSONField(help_text="List of selected sample types"),
                ),
                (
                    "labels_per_type",
                    models.IntegerField(
                        help_text="Number of labels generated per sample type"
                    ),
                ),
                (
                    "total_labels_generated",
                    models.IntegerField(
                        help_text="Total number of labels in the document"
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "label_file",
                    models.FileField(
                        help_text="Generated Word document with labels",
                        upload_to="label_documents/",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description or notes",
                        max_length=500,
                    ),
                ),
                (
                    "transect_codes_generated",
                    models.JSONField(
                        help_text="List of transect codes generated for this batch"
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label_generations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Label Generation",
                "verbose_name_plural": "Label Generations",
                "ordering": ["-generated_at"],
                "permissions": [("generate_labels", "Can generate labels")],
            },
        ),
    ]
