# Generated by Django 5.2.3 on 2025-12-15 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grower_portal", "0029_add_label_generation"),
        ("grower_portal", "0029_csvimportlog_description_csvimportlog_file_path"),
    ]

    operations = []
