# Generated by Django 5.2.3 on 2026-01-06 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_farms_to_fields(apps, schema_editor):
    """Assign farms to any fields that don't have one"""
    Field = apps.get_model('grower_portal', 'Field')
    Farm = apps.get_model('grower_portal', 'Farm')
    GrowerApplication = apps.get_model('grower_portal', 'GrowerApplication')
    
    fields_without_farm = Field.objects.filter(farm__isnull=True)
    
    for field in fields_without_farm:
        application = GrowerApplication.objects.filter(field=field).first()
        
        if application:
            if application.grower:
                farm_name = f'Farm for {application.grower.email or application.grower_name}'
                farm, created = Farm.objects.get_or_create(
                    grower=application.grower,
                    name=farm_name,
                    defaults={'name': farm_name}
                )
            else:
                farm_name = f'Farm for {application.grower_name or "Unknown"}'
                farm, created = Farm.objects.get_or_create(
                    grower=None,
                    name=farm_name,
                    defaults={'name': farm_name}
                )
            field.farm = farm
            field.save()
        else:
            farm, created = Farm.objects.get_or_create(
                grower=None,
                name='Orphaned Field Farm',
                defaults={'name': 'Orphaned Field Farm'}
            )
            field.farm = farm
            field.save()


def reverse_assign_farms_to_fields(apps, schema_editor):
    """Reverse migration - not needed"""


class Migration(migrations.Migration):

    dependencies = [
        ("grower_portal", "0030_merge_20251215_2138"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="farm",
            name="unique_grower_farm_name",
        ),
        migrations.AddField(
            model_name="growerapplication",
            name="created_by_admin",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin user who created this application on behalf of grower",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_created_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="growerapplication",
            name="grower_email",
            field=models.EmailField(
                blank=True,
                help_text="Grower email when no user account exists",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="growerapplication",
            name="grower_name",
            field=models.CharField(
                blank=True,
                help_text="Grower name when no user account exists",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="growerapplication",
            name="grower_phone",
            field=models.CharField(
                blank=True,
                help_text="Grower phone when no user account exists",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="growerapplication",
            name="is_admin_created",
            field=models.BooleanField(
                default=False,
                help_text="Whether this application was created by an admin",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="grower",
            field=models.ForeignKey(
                blank=True,
                help_text="Grower user account (optional for admin-created applications)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="farms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(assign_farms_to_fields, reverse_assign_farms_to_fields),
        migrations.AlterField(
            model_name="field",
            name="farm",
            field=models.ForeignKey(
                help_text="Farm this field belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="grower_portal.farm",
            ),
        ),
        migrations.AlterField(
            model_name="growerapplication",
            name="grower",
            field=models.ForeignKey(
                blank=True,
                help_text="Grower user account (optional if created by admin)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="farm",
            constraint=models.UniqueConstraint(
                fields=("grower", "name"),
                name="unique_grower_farm_name",
                nulls_distinct=True,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="growerapplication",
            name="unique_field_date_sampled",
        ),
        migrations.AlterField(
            model_name="growerapplication",
            name="field",
            field=models.ForeignKey(
                blank=True,
                help_text="Field for this application (created in step 1)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="grower_portal.field",
            ),
        ),
        migrations.AddConstraint(
            model_name="growerapplication",
            constraint=models.UniqueConstraint(
                fields=("field", "date_sampled"),
                name="unique_field_date_sampled",
                nulls_distinct=True,
            ),
        ),
    ]

