# Generated by Django 5.2.3 on 2026-01-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grower_portal", "0033_add_ignite_support"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transectcode",
            options={
                "ordering": ["code"],
                "permissions": [
                    ("generate_transect_codes", "Can generate transect codes")
                ],
                "verbose_name": "Sample Code",
                "verbose_name_plural": "Sample Codes",
            },
        ),
        migrations.AlterField(
            model_name="labelgeneration",
            name="project_type",
            field=models.CharField(
                choices=[("avalanche", "Avalanche"), ("ignite", "Ignite")],
                help_text="Project type (Avalanche or 1000 Farms)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transectcode",
            name="code",
            field=models.CharField(
                help_text="Unique code (transect code for Avalanche, site code for Ignite)",
                max_length=20,
                unique=True,
            ),
        ),
    ]
