# Generated by Django 5.2.3 on 2026-01-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grower_portal", "0037_create_growersamplecodemapping"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="csvimportfieldvalue",
            options={
                "ordering": ["import_log", "sample_code", "field_name"],
                "verbose_name": "CSV Import Field Value",
                "verbose_name_plural": "CSV Import Field Value",
            },
        ),
    ]
