# Generated by Django 5.2.3 on 2026-01-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grower_portal", "0039_growersamplecodemapping_year_sampled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="growersamplecodemapping",
            name="year_sampled",
            field=models.IntegerField(
                help_text="Year the sample was taken (comes from application date_sampled)."
            ),
        ),
    ]
