# Generated by Django 5.2.3 on 2026-02-19 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grower_portal", "0040_alter_growersamplecodemapping_year_sampled"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="csvimportfieldvalue",
            options={
                "ordering": ["row", "field_name", "field_value"],
                "verbose_name": "CSV Import Field Value",
                "verbose_name_plural": "CSV Import Field Value",
            },
        ),
        migrations.RemoveField(
            model_name="csvimportfieldvalue",
            name="import_log",
        ),
        migrations.RemoveField(
            model_name="csvimportfieldvalue",
            name="row_number",
        ),
        migrations.RemoveField(
            model_name="csvimportfieldvalue",
            name="sample_code",
        ),
        migrations.AddField(
            model_name="csvimportlog",
            name="project_type",
            field=models.CharField(
                choices=[("avalanche", "Avalanche"), ("ignite", "Ignite")],
                default="avalanche",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="csvimportlog",
            name="result_type",
            field=models.CharField(
                choices=[("haney", "Haney"), ("plfa", "PLFA"), ("basic", "Basic")],
                default="basic",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CSVImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.IntegerField(blank=True, null=True)),
                ("depth", models.CharField(max_length=255, null=True)),
                (
                    "import_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="grower_portal.csvimportlog",
                    ),
                ),
                (
                    "sample_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="grower_portal.samplecode",
                    ),
                ),
                (
                    "site_transect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="grower_portal.sitetransect",
                    ),
                ),
            ],
            options={
                "verbose_name": "CSV Import Row ",
                "verbose_name_plural": "CSV Import Row",
                "ordering": ["import_log", "sample_code", "site_transect", "depth"],
            },
        ),
        migrations.AddField(
            model_name="csvimportfieldvalue",
            name="row",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="grower_portal.csvimportrow",
            ),
        ),
    ]
