# Generated by Django 5.2.3 on 2026-02-20 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grower_portal", "0040_alter_growersamplecodemapping_year_sampled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="growerapplication",
            name="grower",
            field=models.ForeignKey(
                blank=True,
                help_text="Grower user account (optional if created by admin)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grower_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Grower",
            ),
        ),
    ]
