# Generated by Django 5.2.3 on 2026-02-23 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grower_portal", "0041_alter_csvimportfieldvalue_options_and_more"),
        ("grower_portal", "0041_alter_growerapplication_grower"),
    ]

    operations = []
