# Generated by Django 5.2.3 on 2026-05-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grower_portal", "0042_merge_20260223_2152"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvimportlog",
            name="category",
            field=models.CharField(
                choices=[
                    ("soils", "Soils"),
                    ("water", "Water"),
                    ("plants", "Plants"),
                    ("birds", "Birds"),
                ],
                default="soils",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="csvimportlog",
            name="ingestion_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Internal ingestion data (e.g. birds family_map). Not for admin-facing copy.",
            ),
        ),
        migrations.AlterField(
            model_name="csvimportlog",
            name="result_type",
            field=models.CharField(
                choices=[
                    ("haney", "Haney"),
                    ("plfa", "PLFA"),
                    ("basic", "Basic"),
                    ("birds", "Birds"),
                    ("water", "Water"),
                    ("plants", "Plants"),
                ],
                default="basic",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="csvimportlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("completed_with_errors", "Completed with errors"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
