# Generated by Django 5.2.3 on 2026-06-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grower_portal", "0045_birdrecordingupload"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="birdrecordingupload",
            new_name="grower_port_grower__a44b60_idx",
            old_name="grower_port_grower__a8f2c1_idx",
        ),
        migrations.RenameIndex(
            model_name="birdrecordingupload",
            new_name="grower_port_sample__22455e_idx",
            old_name="grower_port_sample__4e7b2a_idx",
        ),
        migrations.RenameIndex(
            model_name="birdrecordingupload",
            new_name="grower_port_status_65f719_idx",
            old_name="grower_port_status_91c4d0_idx",
        ),
        migrations.AlterField(
            model_name="birdrecordingupload",
            name="year_sampled",
            field=models.IntegerField(
                help_text="Year for S3 path: mapping if present, else SampleCode.year, else current year."
            ),
        ),
        migrations.AlterField(
            model_name="csvimportlog",
            name="category",
            field=models.CharField(
                choices=[
                    ("soils", "Soils"),
                    ("water", "Water"),
                    ("plants", "Plants"),
                    ("birds", "Birds"),
                    ("insects", "Insects"),
                ],
                default="soils",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="csvimportlog",
            name="result_type",
            field=models.CharField(
                choices=[
                    ("haney", "Haney"),
                    ("plfa", "PLFA"),
                    ("basic", "Basic"),
                    ("birds", "Birds"),
                    ("insects", "Insects"),
                    ("water", "Water"),
                    ("plants", "Plants"),
                ],
                default="basic",
                max_length=20,
            ),
        ),
    ]
