
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0046_sync_grower_portal_model_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='growerprofile',
            name='race_indigenous_country',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', 'Select country'),
                    ('US', 'United States'),
                    ('CA', 'Canada'),
                    ('MX', 'Mexico'),
                    ('GT', 'Guatemala'),
                    ('BZ', 'Belize'),
                    ('HN', 'Honduras'),
                    ('SV', 'El Salvador'),
                    ('NI', 'Nicaragua'),
                    ('CR', 'Costa Rica'),
                    ('PA', 'Panama'),
                    ('CU', 'Cuba'),
                    ('JM', 'Jamaica'),
                    ('HT', 'Haiti'),
                    ('DO', 'Dominican Republic'),
                    ('PR', 'Puerto Rico'),
                    ('BR', 'Brazil'),
                    ('AR', 'Argentina'),
                    ('CL', 'Chile'),
                    ('CO', 'Colombia'),
                    ('PE', 'Peru'),
                    ('VE', 'Venezuela'),
                    ('EC', 'Ecuador'),
                    ('BO', 'Bolivia'),
                    ('PY', 'Paraguay'),
                    ('UY', 'Uruguay'),
                    ('GY', 'Guyana'),
                    ('SR', 'Suriname'),
                    ('GB', 'United Kingdom'),
                    ('IE', 'Ireland'),
                    ('FR', 'France'),
                    ('DE', 'Germany'),
                    ('ES', 'Spain'),
                    ('PT', 'Portugal'),
                    ('IT', 'Italy'),
                    ('NL', 'Netherlands'),
                    ('BE', 'Belgium'),
                    ('CH', 'Switzerland'),
                    ('AT', 'Austria'),
                    ('SE', 'Sweden'),
                    ('NO', 'Norway'),
                    ('DK', 'Denmark'),
                    ('FI', 'Finland'),
                    ('IS', 'Iceland'),
                    ('PL', 'Poland'),
                    ('CZ', 'Czech Republic'),
                    ('SK', 'Slovakia'),
                    ('HU', 'Hungary'),
                    ('RO', 'Romania'),
                    ('BG', 'Bulgaria'),
                    ('GR', 'Greece'),
                    ('TR', 'Turkey'),
                    ('RU', 'Russia'),
                    ('UA', 'Ukraine'),
                    ('BY', 'Belarus'),
                    ('LT', 'Lithuania'),
                    ('LV', 'Latvia'),
                    ('EE', 'Estonia'),
                    ('AU', 'Australia'),
                    ('NZ', 'New Zealand'),
                    ('FJ', 'Fiji'),
                    ('PG', 'Papua New Guinea'),
                    ('WS', 'Samoa'),
                    ('TO', 'Tonga'),
                    ('CN', 'China'),
                    ('JP', 'Japan'),
                    ('KR', 'South Korea'),
                    ('IN', 'India'),
                    ('PK', 'Pakistan'),
                    ('BD', 'Bangladesh'),
                    ('LK', 'Sri Lanka'),
                    ('NP', 'Nepal'),
                    ('TH', 'Thailand'),
                    ('VN', 'Vietnam'),
                    ('PH', 'Philippines'),
                    ('ID', 'Indonesia'),
                    ('MY', 'Malaysia'),
                    ('SG', 'Singapore'),
                    ('KH', 'Cambodia'),
                    ('LA', 'Laos'),
                    ('MM', 'Myanmar'),
                    ('TW', 'Taiwan'),
                    ('HK', 'Hong Kong'),
                    ('MN', 'Mongolia'),
                    ('KZ', 'Kazakhstan'),
                    ('UZ', 'Uzbekistan'),
                    ('AF', 'Afghanistan'),
                    ('IR', 'Iran'),
                    ('IQ', 'Iraq'),
                    ('SA', 'Saudi Arabia'),
                    ('AE', 'United Arab Emirates'),
                    ('IL', 'Israel'),
                    ('JO', 'Jordan'),
                    ('LB', 'Lebanon'),
                    ('SY', 'Syria'),
                    ('YE', 'Yemen'),
                    ('OM', 'Oman'),
                    ('KW', 'Kuwait'),
                    ('QA', 'Qatar'),
                    ('BH', 'Bahrain'),
                    ('EG', 'Egypt'),
                    ('LY', 'Libya'),
                    ('TN', 'Tunisia'),
                    ('DZ', 'Algeria'),
                    ('MA', 'Morocco'),
                    ('SD', 'Sudan'),
                    ('ET', 'Ethiopia'),
                    ('KE', 'Kenya'),
                    ('TZ', 'Tanzania'),
                    ('UG', 'Uganda'),
                    ('RW', 'Rwanda'),
                    ('NG', 'Nigeria'),
                    ('GH', 'Ghana'),
                    ('CI', "Côte d'Ivoire"),
                    ('SN', 'Senegal'),
                    ('ML', 'Mali'),
                    ('NE', 'Niger'),
                    ('BF', 'Burkina Faso'),
                    ('CM', 'Cameroon'),
                    ('CD', 'Democratic Republic of the Congo'),
                    ('CG', 'Republic of the Congo'),
                    ('AO', 'Angola'),
                    ('ZA', 'South Africa'),
                    ('ZW', 'Zimbabwe'),
                    ('ZM', 'Zambia'),
                    ('MW', 'Malawi'),
                    ('MZ', 'Mozambique'),
                    ('BW', 'Botswana'),
                    ('NA', 'Namibia'),
                    ('LS', 'Lesotho'),
                    ('SZ', 'Eswatini'),
                    ('MG', 'Madagascar'),
                    ('MU', 'Mauritius'),
                    ('SC', 'Seychelles'),
                ],
                help_text='Country associated with Indigenous / First Nations / Native selection',
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name='growerprofile',
            name='race_other',
            field=models.CharField(
                blank=True,
                help_text='Optional description when Another background is selected',
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name='growerprofile',
            name='race',
            field=models.CharField(
                blank=True,
                choices=[
                    ('white_european', 'White / European'),
                    ('black_african_diaspora', 'Black / African / African diaspora'),
                    ('indigenous_first_nations_native', 'Indigenous / First Nations / Native'),
                    ('east_southeast_asian', 'East or Southeast Asian'),
                    ('south_asian', 'South Asian'),
                    ('middle_eastern_north_african', 'Middle Eastern / North African'),
                    ('latin_american_hispanic_latinx', 'Latin American / Hispanic / Latinx'),
                    ('pacific_islander', 'Pacific Islander'),
                    ('multiple_backgrounds', 'Multiple backgrounds'),
                    ('another_background', 'Another background'),
                    ('prefer_not_to_say', 'Prefer not to say'),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
