# Generated by Django 5.2.3 on 2026-07-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grower_portal', '0048_growerprofile_address_and_country_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvimportlog',
            name='category',
            field=models.CharField(choices=[('soils', 'Soils'), ('water', 'Water'), ('plants', 'Plants'), ('birds', 'Birds'), ('insects', 'Insects'), ('microbiome', 'Microbiome')], default='soils', max_length=20),
        ),
        migrations.AlterField(
            model_name='csvimportlog',
            name='result_type',
            field=models.CharField(choices=[('haney', 'Haney'), ('plfa', 'PLFA'), ('basic', 'Basic'), ('birds', 'Birds'), ('insects', 'Insects'), ('microbiome', 'Amplicon Sequencing'), ('water', 'Water'), ('plants', 'Plants')], default='basic', max_length=20),
        ),
    ]
