# Generated by Django 4.2.14 on 2024-08-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
    ]
