from django.db.models.fields import BLANK_CHOICE_DASH

FIELD_MORPHO_ID = 'id'
FIELD_MORPHO_NAME = 'name'
FIELD_MORPHO_DEFUNT_DATE = 'defunt_date'
FIELD_MORPHO_GBIF_KEY = 'gbif_key'
FIELD_MORPHO_GBIF_CLASS = 'gbif_class'
FIELD_MORPHO_GBIF_ORDER = 'gbif_order'
FIELD_MORPHO_GBIF_FAMILY = 'gbif_family'
FIELD_MORPHO_SUBFAMILY = 'subfamily'
FIELD_MORPHO_GBIF_GENUS = 'gbif_genus'
FIELD_MORPHO_GBIF_SPECIES = 'gbif_species'
FIELD_MORPHO_GBIF_SCIENTIFIC_NAME = 'gbif_scientific_name'
FIELD_MORPHO_GBIF_CANONICAL_NAME = 'gbif_canonical_name'
FIELD_MORPHO_GBIF_RANK = 'gbif_rank'
FIELD_MORPHO_GBIF_STATUS = 'gbif_status'
FIELD_MORPHO_DATE_ADDED = 'date_added'
FIELD_MORPHO_DATE_MODIFIED = 'date_modified'
FIELD_MORPHO_NOTE = 'note'
FIELD_MORPHO_IMAGE = 'image'

MORPHPOSPECIES_THUMBSIZE = 350

# Form fields

FORM_FIELDS_MORPHO = (
    FIELD_MORPHO_NAME,
    FIELD_MORPHO_GBIF_KEY,
    FIELD_MORPHO_GBIF_CLASS,
    FIELD_MORPHO_GBIF_ORDER,
    FIELD_MORPHO_GBIF_FAMILY,
    FIELD_MORPHO_SUBFAMILY,
    FIELD_MORPHO_GBIF_GENUS,
    FIELD_MORPHO_GBIF_SPECIES,
    FIELD_MORPHO_GBIF_SCIENTIFIC_NAME,
    FIELD_MORPHO_GBIF_CANONICAL_NAME,
    FIELD_MORPHO_GBIF_RANK,
    FIELD_MORPHO_GBIF_STATUS,
    FIELD_MORPHO_NOTE,
    FIELD_MORPHO_IMAGE
)

FORM_FIELDS_MORPHO_HIDDEN = (
    FIELD_MORPHO_GBIF_KEY,
    FIELD_MORPHO_GBIF_CLASS,
    FIELD_MORPHO_GBIF_ORDER,
    FIELD_MORPHO_GBIF_FAMILY,
    FIELD_MORPHO_SUBFAMILY,
    FIELD_MORPHO_GBIF_GENUS,
    FIELD_MORPHO_GBIF_SPECIES,
    FIELD_MORPHO_GBIF_SCIENTIFIC_NAME,
    FIELD_MORPHO_GBIF_CANONICAL_NAME,
    FIELD_MORPHO_GBIF_RANK,
    FIELD_MORPHO_GBIF_STATUS,
)

FORM_FIELDS_MORPHO_UPDATE_HIDDEN = (
    FIELD_MORPHO_GBIF_KEY,
)

FORM_FIELDS_MORPHO_REQUIRED = (
    FIELD_MORPHO_NAME,
    FIELD_MORPHO_GBIF_KEY,
    FIELD_MORPHO_GBIF_CANONICAL_NAME
)

# Field Labels

FORM_FIELDS_MORPHO_LABELS = {
    FIELD_MORPHO_NAME: 'Name',
    FIELD_MORPHO_GBIF_CLASS: 'Class',
    FIELD_MORPHO_GBIF_ORDER: 'Order',
    FIELD_MORPHO_GBIF_FAMILY: 'Family',
    FIELD_MORPHO_SUBFAMILY: 'Subfamily',
    FIELD_MORPHO_GBIF_GENUS: 'Genus',
    FIELD_MORPHO_GBIF_SPECIES: 'Species',
    FIELD_MORPHO_GBIF_SCIENTIFIC_NAME: 'Scientific name',
    FIELD_MORPHO_GBIF_CANONICAL_NAME: 'Canonical name',
    FIELD_MORPHO_GBIF_RANK: 'Rank',
    FIELD_MORPHO_GBIF_STATUS: 'Status',
    FIELD_MORPHO_NOTE: 'Note',
}

# HELP TEXT

FORM_MORPHO_HELP_TEXT = {
    FIELD_MORPHO_NAME: 'Name must be unique',
}


# Choices
# These need to be changed to all upper case and in database, thats what GBIF uses.

GBIF_RANK_KINGDOM = 'KINGDOM'
GBIF_RANK_ORDER = 'ORDER'
GBIF_RANK_FAMILY = 'FAMILY'
GBIF_RANK_GENUS = 'GENUS'
GBIF_RANK_SPECIES = 'SPECIES'

GBIF_RANK_CHOICES = (
    BLANK_CHOICE_DASH[0],
    (GBIF_RANK_KINGDOM, GBIF_RANK_KINGDOM),
    (GBIF_RANK_ORDER, GBIF_RANK_ORDER),
    (GBIF_RANK_FAMILY, GBIF_RANK_FAMILY),
    (GBIF_RANK_GENUS, GBIF_RANK_GENUS),
    (GBIF_RANK_SPECIES, GBIF_RANK_SPECIES),
)

GBIF_RANK_CHOICES_WO_BLANK = [v for v in GBIF_RANK_CHOICES if v != BLANK_CHOICE_DASH[0]]
GBIF_RANK_CHOICES_WO_BLANK_LIST = [[v[0], v[1]] for v in GBIF_RANK_CHOICES if v != BLANK_CHOICE_DASH[0]]
GBIF_RANK_VALUES = [v[0] for v in GBIF_RANK_CHOICES]

# EXPORT LIST

EXPORT_HEADERS_MORPHOSPECIES = [
    FIELD_MORPHO_ID,
    FIELD_MORPHO_NAME,
    FIELD_MORPHO_DEFUNT_DATE,
    FIELD_MORPHO_GBIF_KEY,
    FIELD_MORPHO_GBIF_CLASS,
    FIELD_MORPHO_GBIF_ORDER,
    FIELD_MORPHO_GBIF_FAMILY,
    FIELD_MORPHO_SUBFAMILY,
    FIELD_MORPHO_GBIF_GENUS,
    FIELD_MORPHO_GBIF_SPECIES,
    FIELD_MORPHO_GBIF_SCIENTIFIC_NAME,
    FIELD_MORPHO_GBIF_CANONICAL_NAME,
    FIELD_MORPHO_GBIF_RANK,
    FIELD_MORPHO_GBIF_STATUS,
    FIELD_MORPHO_DATE_ADDED,
    FIELD_MORPHO_DATE_MODIFIED,
    FIELD_MORPHO_NOTE,
    FIELD_MORPHO_IMAGE,
]

EXP_MORPH_ALL_MORPH = 'all-morph'
EXP_MORPH_CHOICES = ((EXP_MORPH_ALL_MORPH, 'All Morhpospecies'),)
EXP_MORPH_CHOICES_NAMES = [v[0] for v in EXP_MORPH_CHOICES]
