# Generated by Django 4.2.14 on 2024-07-26 20:17

import uuid

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taxonomy", "0002_alter_morphospecies_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experiment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("name", models.CharField(max_length=1000, unique=True)),
                ("abbreviation", models.SlugField(max_length=20, unique=True)),
                ("from_year", models.PositiveSmallIntegerField()),
                ("to_year", models.PositiveSmallIntegerField()),
                ("leader", models.CharField(max_length=1000)),
                ("no_sites", models.PositiveIntegerField()),
                ("date_per_site", models.PositiveIntegerField()),
                ("completed", models.BooleanField(default=False)),
                ("summary", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "sample_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "---------"),
                            ("aquatic_sweep", "Aquatic sweep"),
                            ("beat_sheet_tray", "Beat sheet/tray"),
                            ("bee_bowl_blue", "Bee bowl (blue)"),
                            ("bee_bowl_color_unknown", "bee bowl (color unknown)"),
                            ("bee_bowl_white", "Bee bowl (white)"),
                            ("bee_bowl_yellow", "Bee bowl (yellow)"),
                            ("blue_vane_trap", "Blue vane trap"),
                            ("dung_core", "Dung core"),
                            ("hand_collection", "Hand collection"),
                            ("malaise_trap", "Malaise trap"),
                            ("quadrat", "Quadrat"),
                            ("soil_core", "Soil core"),
                            ("soil_probe", "Soil probe"),
                            ("vegetation_sweep", "Vegetation sweep"),
                        ],
                        max_length=100,
                    ),
                ),
                ("name_no", models.CharField(blank=True, max_length=100)),
                ("notes", models.CharField(blank=True, max_length=1000)),
                ("completed", models.BooleanField(default=False)),
                ("image", models.ImageField(blank=True, null=True, upload_to="sample_images")),
                ("image_thumbnail", models.ImageField(blank=True, null=True, upload_to="sample_images")),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("site_name", models.CharField(max_length=1000)),
                ("habitat_type", models.CharField(blank=True, max_length=100)),
                ("treatment", models.CharField(blank=True, max_length=100)),
                ("gis_point", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("country", models.CharField(blank=True, max_length=1000)),
                ("state_region", models.CharField(blank=True, max_length=1000)),
                ("county_region", models.CharField(blank=True, max_length=1000)),
                ("us_state_county_fips", models.CharField(blank=True, max_length=5)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                (
                    "experiment",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="samples.experiment"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Specimen",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_modified", models.DateTimeField(auto_created=True, auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("partial_count", models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("confidence", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ("optional_pred_one", models.JSONField(blank=True, default=None, null=True)),
                ("optional_pred_two", models.JSONField(blank=True, default=None, null=True)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=1000), default=list, size=None
                    ),
                ),
                (
                    "acceptance",
                    models.PositiveSmallIntegerField(
                        blank=True, choices=[(0, "Pending"), (1, "Confirmed"), (2, "Rejected")], default=0
                    ),
                ),
                ("archival_identifier", models.CharField(default=None, max_length=1000, null=True, unique=True)),
                ("archival_preservation", models.CharField(blank=True, max_length=100)),
                ("archival_stored", models.CharField(blank=True, max_length=100)),
                (
                    "ai_classification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai",
                        to="taxonomy.morphospecies",
                    ),
                ),
                #(
                #    "ai_version",
                #    models.ForeignKey(
                #        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="taxonomy.aiversion"
                #    ),
                #),
                (
                    "classification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="taxonomy.morphospecies",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="specimens_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer_user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="samples.sample"
                    ),
                ),
            ],
            options={
                "permissions": [("review_specimen_page", "Can use the review specimen page.")],
            },
        ),
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_time", models.DateTimeField(auto_created=True, auto_now_add=True)),
                ("event_title", models.CharField(max_length=200)),
                ("body", models.CharField(blank=True, max_length=1000)),
                (
                    "by_user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("specimen", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="samples.specimen")),
            ],
        ),
        migrations.CreateModel(
            name="SpecimenImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("primary_image", models.BooleanField(default=False)),
                ("image", models.ImageField(upload_to="specimen_images")),
                ("image_thumbnail", models.ImageField(blank=True, null=True, upload_to="specimen_images")),
                ("image_thumbnail_medium", models.ImageField(blank=True, null=True, upload_to="specimen_images")),
                ("image_thumbnail_large", models.ImageField(blank=True, null=True, upload_to="specimen_images")),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("specimen", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="samples.specimen")),
                (
                    "uploaded_by_user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-primary_image"],
            },
        ),
        migrations.CreateModel(
            name="SiteVisit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("visit_date", models.DateField()),
                ("sample_with_plan", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=1000)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("site", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="samples.site")),
            ],
        ),
        migrations.CreateModel(
            name="SamplePlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "sample_type",
                    models.CharField(
                        choices=[
                            ("aquatic_sweep", "Aquatic sweep"),
                            ("beat_sheet_tray", "Beat sheet/tray"),
                            ("bee_bowl_blue", "Bee bowl (blue)"),
                            ("bee_bowl_color_unknown", "bee bowl (color unknown)"),
                            ("bee_bowl_white", "Bee bowl (white)"),
                            ("bee_bowl_yellow", "Bee bowl (yellow)"),
                            ("blue_vane_trap", "Blue vane trap"),
                            ("dung_core", "Dung core"),
                            ("hand_collection", "Hand collection"),
                            ("malaise_trap", "Malaise trap"),
                            ("quadrat", "Quadrat"),
                            ("soil_core", "Soil core"),
                            ("soil_probe", "Soil probe"),
                            ("vegetation_sweep", "Vegetation sweep"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "no_per_date",
                    models.PositiveSmallIntegerField(
                        null=True, validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                ("name_no_per_type", models.CharField(blank=True, max_length=100)),
                (
                    "experiment",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="samples.experiment"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sample",
            name="site_visit",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="samples.sitevisit"),
        ),
    ]
