# Generated by Django 4.2.14 on 2024-08-13 17:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0002_experiment_archived_site_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="gis_point",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
