# Generated by Django 4.2.14 on 2024-08-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0003_alter_site_gis_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="update_thumbs",
            field=models.BooleanField(null=True),
        ),
    ]
