# Generated by Django 4.2.14 on 2024-09-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0004_sample_update_thumbs"),
    ]

    operations = [
        migrations.AddField(
            model_name="specimen",
            name="object_det_train",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="specimenimage",
            name="object_det_sent",
            field=models.DateTimeField(null=True),
        ),
    ]
