# Generated by Django 5.0.9 on 2024-09-27 14:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0005_specimen_object_det_train_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="specimenimage",
            name="multispecimen_image_uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.CreateModel(
            name="MultiSpecimenImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("image", models.ImageField(upload_to="multi_specimen_images")),
                ("image_thumbnail", models.ImageField(blank=True, null=True, upload_to="multi_specimen_images")),
                ("image_grid", models.CharField(choices=[("4-by-3", "4-by-3")], max_length=10)),
                ("cropped_to_specimen", models.BooleanField(null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("sample", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="samples.sample")),
                (
                    "uploaded_by_user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
