# Generated by Django 5.0.9 on 2024-09-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0006_specimenimage_multispecimen_image_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specimenimage",
            name="multispecimen_image_index",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
