# Generated by Django 5.0.9 on 2024-10-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0007_specimenimage_multispecimen_image_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="sample_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "---------"),
                    ("aquatic_sweep", "Aquatic sweep"),
                    ("beat_sheet_tray", "Beat sheet/tray"),
                    ("bee_bowl_blue", "Bee bowl (blue)"),
                    ("bee_bowl_color_unknown", "bee bowl (color unknown)"),
                    ("bee_bowl_white", "Bee bowl (white)"),
                    ("bee_bowl_yellow", "Bee bowl (yellow)"),
                    ("blue_vane_trap", "Blue vane trap"),
                    ("dung_core", "Dung core"),
                    ("hand_collection", "Hand collection"),
                    ("malaise_trap", "Malaise trap"),
                    ("quadrat", "Quadrat"),
                    ("soil_core", "Soil core"),
                    ("soil_probe", "Soil probe"),
                    ("sticky_trap", "Sticky trap"),
                    ("vegetation_sweep", "Vegetation sweep"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="sampleplan",
            name="sample_type",
            field=models.CharField(
                choices=[
                    ("aquatic_sweep", "Aquatic sweep"),
                    ("beat_sheet_tray", "Beat sheet/tray"),
                    ("bee_bowl_blue", "Bee bowl (blue)"),
                    ("bee_bowl_color_unknown", "bee bowl (color unknown)"),
                    ("bee_bowl_white", "Bee bowl (white)"),
                    ("bee_bowl_yellow", "Bee bowl (yellow)"),
                    ("blue_vane_trap", "Blue vane trap"),
                    ("dung_core", "Dung core"),
                    ("hand_collection", "Hand collection"),
                    ("malaise_trap", "Malaise trap"),
                    ("quadrat", "Quadrat"),
                    ("soil_core", "Soil core"),
                    ("soil_probe", "Soil probe"),
                    ("sticky_trap", "Sticky trap"),
                    ("vegetation_sweep", "Vegetation sweep"),
                ],
                max_length=100,
            ),
        ),
    ]
