# Generated by Django 5.0.9 on 2024-11-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0008_alter_sample_sample_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimenimage',
            name='image_notfound',
            field=models.BooleanField(default=False),
        ),
    ]
