# Generated by Django 5.0.9 on 2024-11-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_specimenimage_image_notfound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sampleplan',
            name='sample_type',
            field=models.CharField(max_length=100),
        ),
    ]
