# Generated by Django 5.0.9 on 2024-11-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0010_alter_sample_sample_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='object_det_train',
            field=models.BooleanField(default=False),
        ),
    ]
