# Generated by Django 5.0.9 on 2024-12-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0011_alter_specimen_object_det_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimen',
            name='ai_model_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
