# Generated by Django 5.1.4 on 2025-01-07 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0013_populate_ai_model_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specimen',
            name='ai_version',
        ),
    ]
