# Generated by Django 5.1.4 on 2025-01-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0015_experiment_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimen',
            name='public_image',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
