# Generated by Django 5.1.4 on 2025-02-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0016_specimen_public_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specimen',
            name='public_image',
        ),
        migrations.AddField(
            model_name='specimenimage',
            name='public_image',
            field=models.BooleanField(default=False),
        ),
    ]
