# Generated by Django 5.1.4 on 2025-02-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0018_experiment_exported_file_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimenimage',
            name='downloaded_image',
            field=models.BooleanField(default=False),
        ),
    ]
