# Generated by Django 5.1.4 on 2025-02-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0019_specimenimage_downloaded_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='archival_identifier',
            field=models.CharField(blank=True, default='', max_length=1000),
            preserve_default=False,
        ),
    ]
