# Generated by Django 5.1.4 on 2025-04-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0021_remove_experiment_exported_file_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specimenimage",
            name="object_det_annotation_id",
            field=models.PositiveIntegerField(help_text="From Label Studio", null=True),
        ),
        migrations.AddField(
            model_name="specimenimage",
            name="object_det_id",
            field=models.PositiveIntegerField(help_text="From Label Studio", null=True),
        ),
        migrations.AddField(
            model_name="specimenimage",
            name="object_det_label",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="specimenimage",
            name="object_det_updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
