# Generated by Django 5.1.4 on 2025-05-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0024_userlocationexportfile_experiment"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlocationexportfile",
            name="progress",
            field=models.IntegerField(default=0),
        ),
    ]
