# Generated by Django 5.1.4 on 2025-05-24 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0025_userlocationexportfile_progress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userlocationexportfile",
            name="progress",
        ),
    ]
