# Generated by Django 5.1.4 on 2025-05-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0026_remove_userlocationexportfile_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlocationexportfile",
            name="progress",
            field=models.IntegerField(default=0),
        ),
    ]
