# Generated by Django 5.1.4 on 2025-05-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0029_userlocationexportfile_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="specimenimage",
            name="object_det_model_version",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
