# Generated by Django 5.1.4 on 2025-06-10 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0030_specimenimage_object_det_model_version"),
        ("taxonomy", "0013_gbifimagerecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(
                fields=["sample_type"], name="samples_sam_sample__029233_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sitevisit",
            index=models.Index(
                fields=["visit_date"], name="samples_sit_visit_d_761012_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="specimen",
            index=models.Index(
                fields=["sample"], name="samples_spe_sample__65a1f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="specimen",
            index=models.Index(
                fields=["acceptance"], name="samples_spe_accepta_a06ec3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="specimen",
            index=models.Index(
                fields=["classification"], name="samples_spe_classif_5ab9ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="specimen",
            index=models.Index(
                fields=["ai_classification"], name="samples_spe_ai_clas_902ba1_idx"
            ),
        ),
    ]
