# Generated by Django 5.2.3 on 2025-09-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0031_sample_samples_sam_sample__029233_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="multispecimenimage",
            name="annotations",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="multispecimenimage",
            name="annotations_updated_at",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="multispecimenimage",
            name="panorama_filename",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="multispecimenimage",
            name="predictions",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="multispecimenimage",
            name="predictions_timestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="multispecimenimage",
            name="upload_dir_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="multispecimenimage",
            name="image_grid",
            field=models.CharField(
                blank=True, choices=[("4-by-3", "4-by-3")], max_length=10
            ),
        ),
    ]
