# Generated by Django 5.2.3 on 2025-10-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0032_multispecimenimage_annotations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="multispecimenimage",
            name="label_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="multi_specimen_images"
            ),
        ),
        migrations.AddField(
            model_name="multispecimenimage",
            name="label_image_thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="multi_specimen_images"
            ),
        ),
    ]
