# Generated by Django 5.2.3 on 2025-12-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0036_backfill_specimenimage_dimensions_resumable"),
    ]

    operations = [
        migrations.AddField(
            model_name="multispecimenimage",
            name="annotations_segment",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="multispecimenimage",
            name="annotations_updated_at_segment",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="multispecimenimage",
            name="predictions_coco",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="multispecimenimage",
            name="predictions_timestamp_coco",
            field=models.DateTimeField(null=True),
        ),
    ]
