# Generated by Django 5.2.3 on 2026-01-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0037_multispecimenimage_annotations_segment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specimen",
            name="omit_from_training",
            field=models.BooleanField(default=False),
        ),
    ]
