# model choices
TARGET_16S = '16S'
TARGET_ITS = 'ITS'
TARGET_CHOICES = (
    (TARGET_16S, TARGET_16S),
    (TARGET_ITS, TARGET_ITS)
)
LAB_BIOMMAKERS = 'BiomMakers'
LAB_ECDYSIS_FOUNDATION = 'Ecdysis Foundation'
LAB_CHOICES = ((LAB_BIOMMAKERS, LAB_BIOMMAKERS),)
LAB_ANALYTIC_CHOICES = (
    (LAB_ECDYSIS_FOUNDATION, LAB_ECDYSIS_FOUNDATION),
    (LAB_BIOMMAKERS, LAB_BIOMMAKERS)
)
XLSX = '.xlsx'
CSV = '.csv'
FILE_TYPE_CHOICES = (
    (CSV, CSV),
    (XLSX, XLSX)
)
