#!/bin/bash

set -e

python manage.py collectstatic --noinput --verbosity 3
python -c "import config.wsgi; print('WSGI imported OK')"
exec gunicorn config.wsgi --bind 0.0.0.0:8000 --chdir /app --log-level debug
