# Generated by Django 4.2.14 on 2024-07-26 20:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsCounties",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("statefp", models.CharField(max_length=2)),
                ("countyfp", models.CharField(max_length=3)),
                ("countyns", models.CharField(max_length=8)),
                ("affgeoid", models.CharField(max_length=14)),
                ("geoid", models.CharField(max_length=5)),
                ("name", models.CharField(max_length=100)),
                ("lsad", models.CharField(max_length=2)),
                ("aland", models.BigIntegerField()),
                ("awater", models.BigIntegerField()),
                ("geom", django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name="UsCountiesTigerLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("statefp", models.CharField(max_length=2)),
                ("countyfp", models.CharField(max_length=3)),
                ("countyns", models.CharField(max_length=8)),
                ("geoid", models.CharField(max_length=5)),
                ("name", models.CharField(max_length=100)),
                ("namelsad", models.CharField(max_length=100)),
                ("lsad", models.CharField(max_length=2)),
                ("classfp", models.CharField(max_length=2)),
                ("mtfcc", models.CharField(max_length=5)),
                ("csafp", models.CharField(max_length=3, null=True)),
                ("cbsafp", models.CharField(max_length=5, null=True)),
                ("metdivfp", models.CharField(max_length=5, null=True)),
                ("funcstat", models.CharField(max_length=1)),
                ("aland", models.BigIntegerField()),
                ("awater", models.BigIntegerField()),
                ("intptlat", models.CharField(max_length=11)),
                ("intptlon", models.CharField(max_length=12)),
                ("geom", django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
