# Generated by Django 5.0.9 on 2024-11-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=20)),
                ('entry', models.CharField(max_length=100)),
                ('display_txt', models.CharField(max_length=100)),
            ],
        ),
    ]
