# Generated by Django 5.1.4 on 2025-01-13 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_populate_lookupchoices'),
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookupchoices',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lookup_choices', to='organizations.organization'),
            preserve_default=False,
        ),
    ]
