# Generated by Django 5.1.4 on 2025-02-07 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lookupchoices_organization'),
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField(max_length=30)),
                ('file', models.FileField(upload_to='exports')),
                ('description', models.JSONField(default=dict)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='organizations.organization')),
            ],
        ),
    ]
