# Generated by Django 5.2.3 on 2025-06-18 17:52

import bugbox3.core.customstorage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_exports"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicSiteContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.SlugField(max_length=30, unique=True)),
                (
                    "file",
                    models.FileField(
                        storage=bugbox3.core.customstorage.PublicMediaStorage(),
                        upload_to="site_content",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=500)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
