# Generated by Django 5.2.3 on 2026-01-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_publicsitecontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivateSiteContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.SlugField(max_length=30, unique=True)),
                ("file", models.FileField(upload_to="private_site_content")),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="exports",
            name="file_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publicsitecontent",
            name="file_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
