# Generated by Django 5.2.3 on 2026-06-09 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grower_portal', '0046_sync_grower_portal_model_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrobiomeTaxa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.CharField(choices=[('BiomMakers', 'BiomMakers')], max_length=100)),
                ('lab_analytics_source', models.CharField(choices=[('Ecdysis Foundation', 'Ecdysis Foundation'),], max_length=100)),
                ('file', models.FileField(help_text='User download file', upload_to='microbiome')),
                ('file_type', models.CharField(choices=[('.tsv', '.tsv'),], max_length=10)),
                ('target_region', models.CharField(choices=[('16S', '16S'), ('ITS', 'ITS')], max_length=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteMicrobiomeTaxa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics_sample_id', models.CharField(max_length=100)),
                ('site_code', models.CharField(blank=True, max_length=50)),
                ('user_file', models.FileField(help_text='User download file', upload_to='user_files')),
                ('sample_year', models.PositiveIntegerField()),
                ('num_taxa_found', models.PositiveIntegerField(null=True)),
                ('num_molecular_targets', models.PositiveIntegerField(null=True)),
                ('grower_site_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grower_portal.samplecode')),
                ('parent_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microbiome.microbiometaxa')),
            ],
        ),
    ]
